[package]
name = "day14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "1.0.7"
nom = "7.1.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
