[package]
name = "day15"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixedbitset = "0.4.2"
indoc = "1.0.7"
nom = "7.1.1"
num = "0.4.0"
rayon = "1.6.1"
regex = "1.7.0"
